version: 2
jobs:
  build:
    docker:
      - image: golang:1.13.4

    working_directory: /go/src/github.com/segmentio/orbital

    steps:
      - checkout

      - run:
          name: Run tests
          command: make test
