name: Run Tests
on:
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        go:
          - '1.13.4'
          - '1.17.x'
          - '1.18.x'
          - '1.19.x'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Run Tests
        run: make test
